---
configurations:
- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "CEA"
  rings: "AAA"
  plugboard: ""
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "CEA"
  rings: "AAA"
  plugboard: "AD"
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "CEA"
  rings: "CEA"
  plugboard: "AL"
  ciphertext: HGNCAZM

- action: ENCRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "CEA"
  rings: "AAA"
  plugboard: "AL"
  message: AVELINO

# - action: DECRYPT
#   reflector: UKWB
#   rotors:
#   - 2
#   - 3
#   - 1
#   positions: "CEA"
#   rings: "AAA"
#   ciphertext: HGNCAZM
