---
configurations:
- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "QCW"
  rings: "CEA"
  plugboard: "AD"
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "QCW"
  rings: "EAC"
  plugboard: "AD"
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "AAA"
  rings: "CEA"
  plugboard: "AD"
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "AAA"
  rings: "EAC"
  plugboard: "AD"
  ciphertext: HGNCAZM

- action: DECRYPT
  reflector: UKWB
  rotors:
  - 2
  - 3
  - 1
  positions: "AAA"
  rings: "CEA"
  ciphertext: HGNCAZM
